#!/bin/sh

if [ -e "file/data.db" ]
then
	echo "Not creating database"

else
	echo "Creating database"

	sqlite3 file/data.db "CREATE TABLE TwoLevel (n INT, p REAL, mean REAL, stdDev REAL);"

fi

#For TwoLevel
for i in {0..100..5}
do
	if [ $i -eq 0 ]
	then
		i=1
	fi


		
	echo "Running ${i}"	
	java -cp ".;sqlite-jdbc-3.34.0.jar" src/Main TwoLevel $i
	echo "Finished ${i}"	
	echo
	echo
	
done
