/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_Rnd */

#ifndef _Included_src_Rnd
#define _Included_src_Rnd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_Rnd
 * Method:    createShuffledArray
 * Signature: (ID)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_src_Rnd_createShuffledArray
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     src_Rnd
 * Method:    generateRandomArray
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_src_Rnd_generateRandomArray
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
